// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyOffice.Models;

#nullable disable

namespace MyOffice.Migrations
{
    [DbContext(typeof(EmpInfoContext))]
    [Migration("20250503195418_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyOffice.Models.EmpInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmpDoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("EmpJoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmpInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
